# Generated by Django 4.0.4 on 2022-05-23 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='blocked_by',
            field=models.ManyToManyField(through='blogsite.AppUserBlock', to='blogsite.appuser'),
        ),
        migrations.AddField(
            model_name='appuserblock',
            name='blocked_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_user', to='blogsite.appuser'),
        ),
        migrations.AddField(
            model_name='appuserblock',
            name='blocking_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking_user', to='blogsite.appuser'),
        ),
    ]
